version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/hello-world-python

hooks:
  AfterInstall:
    - location: /home/ec2-user/hello-world-python/app.py
      timeout: 300
      runas: ec2-user
